version: 0.1.2.{build}
branches:
  only:
  - master
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\VersionInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: Nuget packages
deploy:
- provider: NuGet
  server: https://ci.appveyor.com/nuget/fedjabosnic
  api_key:
    secure: mDHR763ncZSdG16EUgXyjLjNfbkjIpbqqVXU82nP+P/kdG3nFXk2elJhiu4Bf0Fd